module.exports = {
  SIYI_CAMERA_UDP_IP_ADDRESS: "192.168.144.25", // REPLACE WITH THE CAMERA's IP ADDRESS
  // SIYI_CAMERA_UDP_IP_ADDRESS: "192.168.68.112", // REPLACE WITH THE CAMERA's IP ADDRESS
  // SIYI_CAMERA_UDP_IP_ADDRESS: "0.0.0.0", // REPLACE WITH THE CAMERA's IP ADDRESS
  // SIYI_CAMERA_UDP_IP_ADDRESS: "10.42.0.1", // REPLACE WITH THE CAMERA's IP ADDRESS
  SIYI_CAMERA_UDP_PORT: 37260, // THIS IS THE DEFAULT PORT CHANGE AS PER NEED
};
